interface FormData {
  productName: string;
  productDescription: string;
  targetAudience: string;
  budget: string;
  goals: string;
}

export class GeminiService {
  private apiKey: string;
  private baseUrl = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent';

  constructor() {
    this.apiKey = import.meta.env.VITE_GEMINI_API_KEY;
    if (!this.apiKey) {
      throw new Error('Gemini API key not found. Please add VITE_GEMINI_API_KEY to your .env file');
    }
  }

  async generateMarketingPlan(formData: FormData): Promise<string> {
    const prompt = this.createPrompt(formData);

    try {
      const response = await fetch(`${this.baseUrl}?key=${this.apiKey}`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: [{
            parts: [{
              text: prompt
            }]
          }],
          generationConfig: {
            temperature: 0.7,
            topK: 40,
            topP: 0.95,
            maxOutputTokens: 8192,
          }
        })
      });

      if (!response.ok) {
        throw new Error(`Gemini API error: ${response.status} ${response.statusText}`);
      }

      const data = await response.json();
      
      if (!data.candidates || !data.candidates[0] || !data.candidates[0].content) {
        throw new Error('Invalid response from Gemini API');
      }

      return data.candidates[0].content.parts[0].text;
    } catch (error) {
      console.error('Error calling Gemini API:', error);
      throw new Error('Failed to generate marketing plan. Please try again.');
    }
  }

  private createPrompt(formData: FormData): string {
    return `You are an expert SaaS marketing strategist. Create a comprehensive, actionable 7-day marketing plan to help acquire the first 100 users for a SaaS product.

Product Details:
- Product Name: ${formData.productName}
- Description: ${formData.productDescription}
- Target Audience: ${formData.targetAudience}
- Marketing Budget: ${formData.budget}
- Primary Goals: ${formData.goals}

Please create a detailed 7-day marketing plan with the following structure:

# 7-Day Marketing Plan for [Product Name]

## Executive Summary
Brief overview of the plan and expected outcomes.

## Product Overview
Summary of the product details provided.

## Day-by-Day Action Plan

### Day 1: [Theme]
**Objective:** [Clear objective]

**Tasks:**
• [Specific actionable task 1]
• [Specific actionable task 2]
• [Specific actionable task 3]
• [Continue with more tasks]

**Expected Outcome:** [Measurable outcome]

[Continue this format for all 7 days]

## Key Metrics to Track

### Primary Metrics:
• [Metric 1 with target]
• [Metric 2 with target]
• [Continue...]

### Secondary Metrics:
• [Secondary metric 1]
• [Secondary metric 2]
• [Continue...]

## Budget Allocation (Based on ${formData.budget})

### Recommended Spend:
• [Category]: [Percentage] - [Description]
• [Category]: [Percentage] - [Description]
• [Continue...]

## Success Factors

### Critical Success Factors:
1. [Factor 1 with explanation]
2. [Factor 2 with explanation]
3. [Continue...]

### Common Pitfalls to Avoid:
• [Pitfall 1]
• [Pitfall 2]
• [Continue...]

## Next Steps After Week 1

### Week 2 Focus Areas:
• [Focus area 1]
• [Focus area 2]
• [Continue...]

### Long-term Strategy:
• [Strategy point 1]
• [Strategy point 2]
• [Continue...]

## Conclusion
Motivational conclusion with key takeaways and next steps.

**Ready to launch? Let's make it happen! 🚀**

---

*Generated by SaaSMarketry Lite - Your AI Marketing Strategist*

Requirements:
1. Make the plan highly specific and actionable for the given product and audience
2. Tailor all strategies to the specified budget range
3. Include realistic timelines and expected outcomes
4. Focus on tactics that can realistically get 100 users in 7 days
5. Use markdown formatting exactly as shown in the structure
6. Be comprehensive but practical
7. Include specific tools, platforms, and tactics relevant to the target audience
8. Make budget recommendations realistic for the specified range
9. Ensure all advice is current and reflects 2024/2025 marketing best practices`;
  }
}